Update CSV field choices
uktrade/enquiry-mgmt-tool pull request #175
Opened 2020-08-20 14:14 UTC by rachaelcodes

## Description of change
Initially, too many fields were being returned to the users when they downloaded the Enquiry list summary CSV. Now only the expected fields are returned.

## Test instructions
From the homepage, click 'Download all'
the following fields should not be included:

- anonymised_project_description
- company_hq_address
- dh_assigned_company_name
- dh_company_address
- dh_company_id
- dh_company_number
- dh_duns_number
- enquirer.id
- id
- investor_involvement_level
- modified
- new_existing_investor
- organisation_type
- owner.date_joined
- owner.email
- owner.id
- owner.is_active
- owner.is_staff
- owner.is_superuser
- owner.last_login
- owner.password
- owner.username
- project_description
- specific_investment_programme

2020-08-20 14:54 UTC, ambrozic requested changes

2020-08-20 14:54 UTC, ambrozic commented on app/enquiries/views.py
> +class EnquiryListCSVRenderer (CSVRenderer):
there is a space after class name

2020-08-20 14:54 UTC, ambrozic commented on app/enquiries/tests/test_views.py
> +        assert response.content.decode('UTF-8').strip() == ','.join(
`utf-8` is default value for encoding. no need to specify it.

2020-08-20 15:45 UTC, rafenden approved these changes

2020-08-20 15:45 UTC, rafenden approved these changes
Pending Gregor's comments.

2020-08-20 16:15 UTC, rachaelcodes commented on app/enquiries/views.py
> +class EnquiryListCSVRenderer (CSVRenderer):
I might also have a look into why Flake8 didn't pick that up.

2020-08-21 07:05 UTC, ambrozic commented on app/enquiries/views.py
> +class EnquiryListCSVRenderer (CSVRenderer):
let me know what was wrong. tried it in datahub api repo and flake8 also ignores this issue.

2020-08-21 07:05 UTC, ambrozic approved these changes

2020-08-21 08:04 UTC, merged