Draft: Add command to mark stale enquiries as 'Non-responsive'
uktrade/enquiry-mgmt-tool pull request #178
Opened 2020-08-24 15:23 UTC by rachaelcodes

## Description of change
Adds a command that checks whether an enquiry is over six weeks old and has a status of 'Awaiting response' (I'm double-checking the logic with Aleesha about whether this should be six weeks since creation or editing). In this case, the enquiry is marked as 'Non responsive'.

Also adds a celery task to run this command daily.

## Test instructions
If running locally, check the numbers of enquiries with 'Awaiting response' and 'Non responsive' added using the filters.
Run the command with `python manage.py mark_non_responsive_enquiries`, and note the number of enquiries changed.
Check the new number of enquiries with 'Awaiting response' and 'Non responsive'.

2020-08-24 16:40 UTC, mforner13 commented on app/enquiries/tasks.py
> +def update_enquiry_stage():
I think the task name could be a bit more specific so it's easy to recognise its purpose in the logs - e.g. `update_stage_stale_enquiries`

2020-08-24 16:46 UTC, mforner13 commented on sample_env
>  REDIS_BASE_URL=redis://localhost:6379
Could update the base url in a separate commit in this PR? 😃

2020-08-25 08:39 UTC, rachaelcodes commented on sample_env
>  REDIS_BASE_URL=redis://localhost:6379
haha great minds - I'd put it in and not pushed the changes :D

2020-08-25 10:37 UTC, mforner13 approved these changes
Looks good! 👍  Just one small thing - the commit message could give more information about what the changes are doing like in the PR title

2020-08-25 11:12 UTC, ambrozic requested changes

2020-08-25 11:12 UTC, ambrozic commented on app/enquiries/celery.py
> +ENQUIRY_STATUS_UPDATE_INTERVAL_DAYS = settings.ENQUIRY_STATUS_UPDATE_INTERVAL_DAYS
This variable suggests to define and interval in days but is later used to schedule a task on a day in month. Would variable name like `ENQUIRY_STATUS_UPDATE_DAY_IN_MONTH` be more clear? Or maybe even `ENQUIRY_STATUS_UPDATE_TASK_SCHEDULE='*/15'`?

2020-08-25 12:30 UTC, rachaelcodes commented on app/enquiries/celery.py
> +ENQUIRY_STATUS_UPDATE_INTERVAL_DAYS = settings.ENQUIRY_STATUS_UPDATE_INTERVAL_DAYS
It's used with '*/' for every X days per 'day of the month', but if it's not clear, I'll update it to `ENQUIRY_STATUS_UPDATE_DAILY_SCHEDULE='*/1'` and then also update the other interval names to keep them consistent.

2020-08-25 12:40 UTC, ambrozic commented on app/enquiries/celery.py
> +ENQUIRY_STATUS_UPDATE_INTERVAL_DAYS = settings.ENQUIRY_STATUS_UPDATE_INTERVAL_DAYS
is the task suppose to be running every X days or once a month on Xth day in month?

2020-08-25 12:46 UTC, rachaelcodes commented on app/enquiries/celery.py
> +ENQUIRY_STATUS_UPDATE_INTERVAL_DAYS = settings.ENQUIRY_STATUS_UPDATE_INTERVAL_DAYS
Every X days - but day={frequency} doesn't seem to be an option.

2020-08-25 12:50 UTC, ambrozic approved these changes

2020-08-25 14:51 UTC, merged