Enquiry service -  adobe campaign integration
uktrade/enquiry-mgmt-tool pull request #196
Opened 2020-09-25 00:15 UTC by harel

## Description of change

This update adds the integration between EMT and Adobe campaign. 
Non responsive leads from great invest, who are marked as non responsive, are added to an email campaign 
inviting them to fill a second qualification form and request a call back from DIT. 
Once contacted and deemed engaged, nurturing is no longer required and the lead is removed from the campaign. 

This project as a whole spans this service (EMT), legal consent and the 2nd qualification form resides in great-international-ui and forms api. 

## Test instructions

There is no visible changes per-se but the flow is as so: 

1. periodically collect all non responsive enquiries since the last cycle. 
2. for each enquiry, add the lead to a staging area in Adobe Campaign. Follow by initiating the workflow in Adobe to process these. 
3. collect any submissions of the second qualification form from forms-api / activity stream. For each submission, create update records in the staging table in adobe. 
4. collect any enquiries marked as sent to post, the exit criteria, and unsubscribe them from the campaign.

2020-09-25 15:17 UTC, ambrozic requested changes

2020-09-25 15:17 UTC, ambrozic commented on app/enquiries/common/email_campaign_utils.py
> +ENQUIRY_SOURCE 'EMT'
`=` is probably missing

2020-09-25 15:17 UTC, ambrozic commented on app/enquiries/common/email_campaign_utils.py
> +    successfuly.
typo

2020-09-25 15:17 UTC, ambrozic commented on app/enquiries/common/adobe.py
> +    def create_staging_profile(self, email=None, first_name=None, last_name=None, emt_id=None, extra_data=None, **kwargs):
this line is probably too long and might enrage certain people

2020-09-25 15:17 UTC, ambrozic commented on app/enquiries/common/email_campaign_utils.py
> +    #     logger.info(f'Processed enquiry {enquiry}')
not sure if code in this function above is finished?

2020-09-25 15:17 UTC, ambrozic commented on app/enquiries/common/email_campaign_utils.py
> +    return crypto.get_random_string(size)
is this one line function really necessary?

2020-09-25 15:17 UTC, ambrozic commented on app/enquiries/common/email_campaign_utils.py
> +    return log
same as above

2020-09-25 15:17 UTC, ambrozic commented on app/enquiries/models.py
> +
one newline too many

2020-09-25 15:17 UTC, ambrozic commented on app/enquiries/tasks.py
> +
this can be removed

2020-09-25 15:17 UTC, ambrozic commented on app/enquiries/tasks.py
> +
too many empty lines

2020-09-25 15:17 UTC, ambrozic commented on app/settings/common.py
> +ACTIVITY_STREAM_ENQUIRY_SEARCH_VALUE3 = env('ACTIVITY_STREAM_ENQUIRY_SEARCH_VALUE3')
missing empty line at the end of the file

2020-09-25 15:25 UTC, ambrozic requested changes

2020-09-25 15:25 UTC, ambrozic commented on app/enquiries/common/email_campaign_utils.py
> +    return log
if adobe client raises an error, `log` here will be undefined and error with `UnboundLocalError`

2020-09-28 09:26 UTC, mforner13 requested changes
Looks good overall, have requested some mainly cosmetic changes. It's just missing tests - unit and integration if possible with Adobe campaign.

2020-09-28 09:26 UTC, mforner13 commented on app/enquiries/common/email_campaign_utils.py
> +This module handles the connection to Adobe Campaign, subscribing non responsinve leads
Typo in responsive

2020-09-28 09:26 UTC, mforner13 commented on app/enquiries/common/email_campaign_utils.py
> +2. For each one, subscribe the lead to the adobe campaign.
I think it would be best to refer to them as `enquirers` as is done in the rest of the app, rather than leads, to avoid confusion.

2020-09-28 09:26 UTC, mforner13 commented on app/enquiries/common/email_campaign_utils.py
> +        logger.info(f'Processed enquiry {enquiry}')
Would it be useful to log the number of enquiries processed here?

2020-09-28 09:26 UTC, mforner13 commented on app/enquiries/common/email_campaign_utils.py
> +    #     logger.info(f'Processed enquiry {enquiry}')
It seems like at this point the stage of the enquiry should change, as if they have submitted the 2nd qualification form they are no longer non-responsive. Apologies if this is done elsewhere and I've missed it.

2020-09-28 09:26 UTC, mforner13 commented on app/enquiries/common/email_campaign_utils.py
> +    logger.info("Processing enquiry. Email=%s", email)
Could you use string interpolation here as you have with other logger outputs?

2020-09-28 09:26 UTC, mforner13 commented on app/enquiries/common/email_campaign_utils.py
> +        logger.exception('Error creating staging profiles in Adobe: %s', str(exc))
Same as comment above - an 'f' string would be neater.

2020-09-28 09:26 UTC, mforner13 commented on app/enquiries/models.py
> +    enquiry = models.ForeignKey(Enquiry, null=False, blank=False, on_delete=models.PROTECT)
`null` and `blank` both default to `False` so not necessary to specify.

2020-09-28 09:26 UTC, mforner13 commented on app/enquiries/models.py
> +    def action_date_boundary(action):
A name like `get_last_action_date` could be clearer here?

2020-09-28 12:54 UTC, harel commented on app/enquiries/common/adobe.py
> +        Standard request headrs
fixed, thanks

2020-09-28 12:55 UTC, harel commented on app/enquiries/common/adobe.py
> +        if emt_id:
just defensive programming.

2020-09-28 12:55 UTC, harel commented on app/enquiries/common/adobe.py
> +        if emt_id:
i can remove it though it doesn't hurt :-)

2020-09-28 12:56 UTC, harel commented on app/enquiries/common/adobe.py
> +    def subscribe(self, service_pkey, profile_pkey=None, subscribe_url=None):
true. added.

2020-09-28 12:57 UTC, harel commented on app/enquiries/common/adobe.py
> +        Return a single service by it's pkey
where is the embarrassed icon....

2020-09-28 12:59 UTC, harel commented on app/enquiries/common/email_campaign_utils.py
> +    logger.info("Processing enquiry. Email=%s", email)
Actually i intend to change the other ones to the correct logger format of using %s style tags.

2020-09-28 12:59 UTC, harel commented on app/enquiries/common/email_campaign_utils.py
> +    logger.info("Processing enquiry. Email=%s", email)
This method is not done - it's the  piece i'm still working on .

2020-09-28 13:00 UTC, harel commented on app/enquiries/models.py
> +    enquiry = models.ForeignKey(Enquiry, null=False, blank=False, on_delete=models.PROTECT)
just a habit of having it clearly defined...

2020-09-28 13:00 UTC, harel commented on app/enquiries/models.py
> +    def action_date_boundary(action):
:) that was the original name. i'll change

2020-09-29 08:20 UTC, mforner13 commented on app/enquiries/common/adobe.py
> +        if emt_id:
Ah no you're right, it doesn't hurt :)

2020-09-29 13:43 UTC, elcct commented on app/enquiries/common/adobe.py
> +            "aud": f"https://ims-na1.adobelogin.com/c/{settings.ADOBE_API_KEY}",
I think it could be a good idea to have this URL as a environment variable as well so that when it changes in the future it will be more convenient to amend it.

2020-09-29 13:48 UTC, elcct commented on app/enquiries/common/adobe.py
> +        return f"https://mc.adobe.io/{settings.ADOBE_TENANT_ID}/campaign/{path}"
Maybe this template could also be changeable using an environment variable?

2020-09-29 23:51 UTC, harel commented on app/enquiries/common/email_campaign_utils.py
> +    logger.info("Processing enquiry. Email=%s", email)
this is now more complete

2020-09-29 23:55 UTC, harel commented on app/enquiries/common/adobe.py
> +            "aud": f"https://ims-na1.adobelogin.com/c/{settings.ADOBE_API_KEY}",
done

2020-09-29 23:57 UTC, harel commented on app/enquiries/common/adobe.py
> +        return f"https://mc.adobe.io/{settings.ADOBE_TENANT_ID}/campaign/{path}"
done

2020-09-30 00:00 UTC, harel commented on app/enquiries/common/email_campaign_utils.py
> +2. For each one, subscribe the lead to the adobe campaign.
done

2020-09-30 00:03 UTC, harel commented on app/enquiries/common/email_campaign_utils.py
> +        logger.info(f'Processed enquiry {enquiry}')
could be. added

2020-09-30 12:44 UTC, mforner13 reviewed
Just a couple more comments. Once this is merged - please could you add details of the tool's integration with Adobe Campaigns to [the DIT manual](https://readme.trade.gov.uk/docs/playbooks/enquiry-management.html#service-dependencies). :)

2020-09-30 12:44 UTC, mforner13 commented on app/enquiries/common/adobe.py
> +        Subscribe a profile to a campaign. This method was implemented but will not be used
Is there any advantage of keeping this method in this codebase if it won't be used?

2020-09-30 12:44 UTC, mforner13 commented on app/enquiries/common/email_campaign_utils.py
> +    return crypto.get_random_string(size)
@harel can this be removed?

2020-09-30 12:44 UTC, mforner13 commented on app/enquiries/common/email_campaign_utils.py
> +    longer required nurture. The lead will be unsubscribed from the campaign
Typo - requires nurturing?

2020-09-30 12:44 UTC, mforner13 commented on app/enquiries/tests/test_adobe_integration.py
> +        self.enquiry = Enquiry.objects.create(
Could you use the `EnquirerFactory` and `EnquiryFactory` for these instead? in `enquiries/tests/factories.py`

2020-09-30 18:47 UTC, harel commented on app/enquiries/common/adobe.py
> +        Subscribe a profile to a campaign. This method was implemented but will not be used
it's not used in this particular use case, but it might be in other's if adobe campaign is used elsewhere. this client, at some point, should be moved into it's own repo and be installable. This is a bit out of scope for this but it's a nice thing to have in future. The current iteration is specifically tailored to our use case here with the use of the staging area in adobe.

2020-09-30 18:48 UTC, harel commented on app/enquiries/common/email_campaign_utils.py
> +    longer required nurture. The lead will be unsubscribed from the campaign
I'm obviously a non-believer in the backspace...

2020-09-30 19:21 UTC, harel commented on app/enquiries/tests/test_adobe_integration.py
> +        self.enquiry = Enquiry.objects.create(
Actually, I tried but it's not working out. I need the test data in the db, not mocked, for the process to work. the factories are transient records that i cannot 'query' later.

2020-09-30 19:38 UTC, harel commented
https://github.com/uktrade/rtfm/pull/341

2020-10-01 09:16 UTC, mforner13 approved these changes
👍

2020-10-01 10:04 UTC, ambrozic requested changes

2020-10-01 10:16 UTC, ambrozic approved these changes

2020-10-01 10:17 UTC, elcct commented on .coveragerc
> +    app/enquiries/common/adobe.py
Would be great to add a line end.

2020-10-01 10:17 UTC, elcct approved these changes

2020-10-01 21:07 UTC, merged