Fixes related to handling of second qualification forms
uktrade/enquiry-mgmt-tool pull request #204
Opened 2020-10-08 09:21 UTC by harel

## Description of change

use an isoformated date for as search. 
check if emt was provided in second qual form. 
use just date when filtering for second qual to catch discrepancies between log date and 2nd qual submission

2020-10-08 09:44 UTC, mforner13 commented on app/enquiries/common/email_campaign_utils.py
> +            return log
What's the purpose of returning `None` here and on line 177? If the return value doesn't matter can we just `return`?

2020-10-08 10:29 UTC, harel commented on app/enquiries/common/email_campaign_utils.py
> +            return log
It's just a habit. In a happy path it returns the log object , which is useful if you're testing or debugging. So as a habit if i return something, i try to return None explicitly if there is a None value to return . 
I can change to an empty return if that works better for you though. i don't mind

2020-10-08 10:51 UTC, peterhudec requested changes
Looks good, just a couple of things.

2020-10-08 10:51 UTC, peterhudec commented on app/enquiries/common/email_campaign_utils.py
> +            return log
The return value doesn't seem to be used apart from a test, where `None` is asserted, so the `log` variable can be removed.

2020-10-08 10:51 UTC, peterhudec commented on app/enquiries/tests/test_adobe_integration.py
> +        assert log is None
This kind of tests are of little value as it only checks one specific scenario. I would remove it.

2020-10-08 10:51 UTC, peterhudec commented on app/enquiries/common/email_campaign_utils.py
> +        return log
This check should be done outside of the function and the function should only be called if `emt_id` is not `None`. The `emt_id` is after all defined as a _required_ parameter.

2020-10-08 10:56 UTC, harel commented on app/enquiries/tests/test_adobe_integration.py
> +        assert log is None
i only tried to get it in because coverage was complaining.

2020-10-08 11:02 UTC, mforner13 commented on app/enquiries/tests/test_adobe_integration.py
> +        assert log is None
As codecov passing is not mandatory for the PR to be merged, I'd say best to remove this if it's only to placate the check, so as not to give false reassurance?

2020-10-08 14:47 UTC, mforner13 approved these changes

2020-10-09 12:21 UTC, peterhudec approved these changes

2020-10-09 12:21 UTC, merged