Enquiry ID filter
uktrade/enquiry-mgmt-tool pull request #206
Opened 2020-10-14 17:58 UTC by harel

Add an enquiry id filter. This helps users locate an enquiry based on
the id and is useful for locating submissions of second qualification
forms.

## Description of change

Adds a new filter search field, and subsequent filter definition

## Test instructions

In the enquiries screen a new field should show at the bottom of the filter list.

2020-10-15 07:21 UTC, ambrozic approved these changes

2020-10-15 08:54 UTC, mforner13 commented on app/enquiries/templates/partials/enquiry_filters.html
> +    <label class="govuk-label" for="project_code__icontains">
The `for` needs updating to match `emt_id`

2020-10-15 08:55 UTC, mforner13 commented on app/enquiries/views.py
> +    id = filters.NumberFilter(field_name="id", method="filter_id")
Could specify `enquiry__id` just to make it super clear? And given we've got `owner__id` too.

2020-10-15 08:57 UTC, mforner13 requested changes
A couple of suggestions, but mainly there needs to be tests added for the new filter. 

There's functional tests for the other filters in `filter.test.js`and unit in `test_filters.py`.

2020-10-19 12:40 UTC, harel commented on app/enquiries/views.py
> +    id = filters.NumberFilter(field_name="id", method="filter_id")
This would break the filter i think.... it's based on the field name and it's path in the objects.

2020-10-22 10:37 UTC, mforner13 approved these changes

2020-10-22 12:58 UTC, merged