Bugfix: prevent duplicate contact creation
uktrade/enquiry-mgmt-tool pull request #211
Opened 2020-11-27 16:58 UTC by rachaelcodes

## Description of change
Fixes a bug whereby if company contacts known to Data Hub made enquiries that were fed through the EMT, a duplicate contact would be created.

Now when preparing to submit to Data Hub, there is a check to see if the enquirer's first name, last name and email is an exact match to any of the existing contacts in Data Hub (business logic here agreed by Nitesh). If there is an exact match, this contact's id is used in submitting the enquiry to DH, otherwise a new company contact is created first. 

If there are no existing contacts for the company, the new contact created here will be labeled as a 'Primary' contact.

## Test instructions
If running locally using the default api fixtures: 

- create a new enquiry
- link this enquiry to 'Venus Ltd' in your local DH instance
- make sure the enquirer's name is: `Johnny Cakeman` with the email address: `johnny@cakeman.com`
- add the enquiry to DataHub (locally)
- check that the enquiry has been added to DH
- check that a duplicate Johnny Cakeman has not been added to the database

2020-11-27 17:00 UTC, rachaelcodes commented on app/enquiries/common/datahub_utils.py
> -def dh_contact_search(request, access_token, contact_name, company_id):
This wasn't doing what was described: there's a fuzzy match on the name in the DH search, so it could falsely identify duplicates.

The output of this function was also being used to identify not whether there were matching contacts in the company, but any contacts at all - which is why I've removed the contact name parameter.

2020-11-27 17:00 UTC, rachaelcodes commented on app/enquiries/common/datahub_utils.py
> -    payload = {"name": contact_name, "company": [company_id]}
see comment above for why this was removed

2020-11-27 17:01 UTC, rachaelcodes commented on app/enquiries/common/datahub_utils.py
> -    enquirer = enquirer.enquirer
It seemed clearer to just pass the enquiry.enquirer object in directly

2020-11-27 17:03 UTC, rachaelcodes commented on app/enquiries/common/datahub_utils.py
> -    existing_contacts, error = dh_contact_search(request, access_token, full_name, company_id)
I'm not sure it made sense to pass in an enquirer name to a search that was used to see whether there were any contacts in that company.

2020-11-27 17:04 UTC, rachaelcodes commented on app/enquiries/tests/test_dh_integration.py
> -        "error": {"name": ["This field may not be blank."]},
Updated to reflect the actual api error messages

2020-11-27 17:04 UTC, rachaelcodes commented on app/enquiries/tests/test_dh_integration.py
> -    def test_contact_search_error(self):
Removed as this is not how the api seems to behave

2020-11-30 08:26 UTC, ambrozic requested changes

2020-11-30 08:26 UTC, ambrozic commented on app/enquiries/common/datahub_utils.py
> +def prepare_dh_contact(request, access_token, enquirer, company_id):
could this be renamed to `dh_contact_prepare` for the sake of naming consistency in this module?

2020-11-30 08:26 UTC, ambrozic commented on app/enquiries/common/datahub_utils.py
> +    :type company_id: uuid
is `company_id` `uuid` or `str`? in code and in tests it is used and passed around as `str`

2020-11-30 08:26 UTC, ambrozic commented on app/enquiries/common/datahub_utils.py
> +        return None, {"contact_search": f"Error while checking company contacts, {str(error)}"}
does `error` have to be cast to `str`?

2020-11-30 08:27 UTC, ambrozic commented
is it possible there will be issues, at least in emails, with case sensitivity?

2020-12-02 08:31 UTC, rachaelcodes commented on app/enquiries/common/datahub_utils.py
> +def prepare_dh_contact(request, access_token, enquirer, company_id):
Yes, there's a `prepare_dh_payload` elsewhere in the file which this was copying, but what I'll do is bring them both round to this style.

2020-12-02 08:44 UTC, rachaelcodes commented on app/enquiries/common/datahub_utils.py
> +        return None, {"contact_search": f"Error while checking company contacts, {str(error)}"}
This is the pattern through the rest of the 'submit to DataHub' functions - I think the idea is that the error messages are passed as strings to view to populate the error information box for users.

2020-12-02 08:48 UTC, rachaelcodes commented
> is it possible there will be issues, at least in emails, with case sensitivity?

Good shout. I'll cancel out the case on the names too, as some are entered in all-caps, and sometimes people are lazy with capital letters.

2020-12-02 09:05 UTC, ambrozic commented on app/enquiries/common/datahub_utils.py
> +        return None, {"contact_search": f"Error while checking company contacts, {str(error)}"}
in the similar code below errors are not casted to string. error object seem to be dict or exception and when string-formatted, this objects are converted to string by default without issues.

2020-12-02 09:18 UTC, ambrozic approved these changes

2020-12-02 09:47 UTC, mcbhenwood approved these changes

2020-12-02 09:47 UTC, mcbhenwood commented on app/enquiries/common/datahub_utils.py
> +            and company_contact["email"].lower() == email.lower()
I'd argue that the name checks are redundant if the email matches, but I note the agreed logic in the PR header so OK.

2020-12-02 09:47 UTC, mcbhenwood commented on app/enquiries/common/datahub_utils.py
> +    :returns: A subset of fields for each company found
Returns a matching contact.

2020-12-02 14:16 UTC, merged